In [1]:
import numpy as np

def create_matrix(x):
    x0 = np.ones([x.shape[0],1])
    return np.hstack([x0, x])

In [10]:
def sigmoid(X, parameter):
    return 1 /(1 + np.exp(-np.dot(X, parameter)))

In [3]:
def logistic_regression(X, t):
    LNR = 1e-1
    loop = 50
    count = 1
    parameter = np.random.rand(3)
    
    for i in range(loop):
        parameter = parameter - LNR*np.dot(sigmoid(X,parameter)- t, X)
        if (count == 1 or count % 10 ==0):
            print("{}回: parameter = {}".format(count, parameter))
        count += 1
    return parameter

In [11]:
# AND gate
x = np.array([[0,0],[0,1],[1,0],[1,1]])
t = np.array([0,0,0,1])
X = create_matrix(x)
parameter = logistic_regression(X,t)

1回: parameter = [-0.08599194  0.38742704  0.19842216]
10回: parameter = [-0.81937827  0.3913368   0.24012404]
20回: parameter = [-1.23260095  0.57876284  0.45861722]
30回: parameter = [-1.53806506  0.78290118  0.68644434]
40回: parameter = [-1.80221546  0.97258005  0.89465754]
50回: parameter = [-2.04136885  1.14514557  1.0818575 ]


In [12]:
(sigmoid(create_matrix(np.array([[0,0],[0,1],[0,0],[1,1]])), parameter)>= 0.5).astype(np.int)

/var/folders/ks/dtzw0jpn5_zd7nz4v999tjm00000gn/T/ipykernel_39887/137009639.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (sigmoid(create_matrix(np.array([[0,0],[0,1],[0,0],[1,1]])), parameter)>= 0.5).astype(np.int)


array([0, 0, 0, 1])

In [6]:
# NAND gate
x = np.array([[0,0],[0,1],[1,0],[1,1]])
t = np.array([1,1,1,0])
X = create_matrix(x)
parameter = logistic_regression(X,t)

1回: parameter = [0.09447158 0.00077377 0.60251457]
10回: parameter = [ 0.5563592  -0.20073068  0.28579522]
20回: parameter = [ 0.93748452 -0.44059803 -0.05310831]
30回: parameter = [ 1.25991435 -0.66089311 -0.3506344 ]
40回: parameter = [ 1.54678768 -0.8581074  -0.60851519]
50回: parameter = [ 1.80675023 -1.03558611 -0.8338241 ]


In [7]:
(sigmoid(create_matrix(np.array([[0,0],[0,1],[0,0],[1,1]])), parameter)>= 0.5).astype(np.int)

/var/folders/ks/dtzw0jpn5_zd7nz4v999tjm00000gn/T/ipykernel_39887/137009639.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (sigmoid(create_matrix(np.array([[0,0],[0,1],[0,0],[1,1]])), parameter)>= 0.5).astype(np.int)


array([1, 1, 1, 0])

In [8]:
# OR gate
x = np.array([[0,0],[0,1],[1,0],[1,1]])
t = np.array([0,1,1,1])
X = create_matrix(x)
parameter = logistic_regression(X,t)

1回: parameter = [0.92011922 0.26673731 0.76494044]
10回: parameter = [0.72950989 0.56608994 1.000276  ]
20回: parameter = [0.51565983 0.85559648 1.23040922]
30回: parameter = [0.3183897  1.11509661 1.43991162]
40回: parameter = [0.14191986 1.35154567 1.63403532]
50回: parameter = [-0.01477737  1.56879547  1.81540848]


In [9]:
(sigmoid(create_matrix(np.array([[0,0],[0,1],[0,0],[1,1]])), parameter)>= 0.5).astype(np.int)

/var/folders/ks/dtzw0jpn5_zd7nz4v999tjm00000gn/T/ipykernel_39887/137009639.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (sigmoid(create_matrix(np.array([[0,0],[0,1],[0,0],[1,1]])), parameter)>= 0.5).astype(np.int)


array([0, 1, 0, 1])